In [272]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [273]:
inc2016_file = "./Resources/inc5000_2016.csv"
inc2016_df = pd.read_csv(inc2016_file)
inc2016_df.dropna(axis=1, how='all')

,id,rank,workers,company,url,state_l,state_s,city,growth,revenue,ifmid,ifiid,metro,industry,yrs_on_list
0,42940,1,218,Loot Crate,loot-crate,California,CA,Los Angeles,66788.5962,116247698,2.0,4,Los Angeles,Consumer Products & Services,1
1,42941,2,100,Paint Nite,paint-nite,Massachusetts,MA,Somerville,36555.2472,55018793,6.0,4,Boston,Consumer Products & Services,1
2,42942,3,47,CalCom Solar,calcom-solar,California,CA,Visalia,31633.5448,33507450,172.0,16,"Visalia-Porterville, CA",Energy,1
3,36643,4,82,eLuxurySupply.com,eluxurysupplycom,Indiana,IN,Evansville,23619.7198,30695215,641.0,18,"Evansville, IN-KY",Retail,2
4,36639,5,48,Company.com,companycom,Georgia,GA,Atlanta,23486.8894,33370967,29.0,17,Atlanta,Business Products & Services,2
5,42943,6,15,Globalization Partners,globalization-partners,Massachusetts,MA,Cambridge,16196.5338,17743829,6.0,17,Boston,Business Products & Services,1
6,42944,7,130,Bounce Exchange,bounce-exchange,New York,NY,New York,14574.6474,15733570,9.0,9,New York City,Software,1
7,42945,8,25,Los York,los-york,California,CA,Santa Monica,14404.6093,15598837,2.0,5,Los Angeles,Advertising & Marketing,1
8,42946,9,39,PANTHERx Specialty Pharmacy,pantherx-specialty-pharmacy,Pennsylvania,PA,Pittsburgh,13380.8799,42425003,52.0,10,"Pittsburgh, PA",Health,1
9,42947,10,9,FedBiz IT Solutions,fedbiz-it-solutions,Virginia,VA,Leesburg,12620.5845,25863238,3.0,7,"Washington, DC",Government Services,1
10,42948,11,14,Small Business Owners of America,small-business-owners-of-america,Ohio,OH,Columbus,12059.8622,12369863,19.0,2,"Columbus, OH",Financial Services,1
11,42949,12,52,PLANIT GROUP,planit-group,North Carolina,NC,Charlotte,11525.3681,11518066,43.0,8,Charlotte,IT Services,1
12,42950,13,250,Suja Juice,suja-juice,California,CA,San Diego,10511.0846,65877327,11.0,11,San Diego,Food & Beverage,1
13,42951,14,105,S2 Capital,s2-capital,Texas,TX,Addison,9645.7324,28804779,8.0,3,Dallas,Real Estate,1
14,37197,15,35,FormulaFolio Investments,formulafolio-investments,Michigan,MI,Grand Rapids,9400.5092,11212596,219.0,2,"Grand Rapids-Wyoming, MI",Financial Services,2
15,42952,16,171,Persado,persado,New York,NY,New York,9389.7747,17432811,9.0,9,New York City,Software,1
16,42953,17,15,Berkley,berkley,California,CA,Carson,9249.2602,11449478,2.0,15,Los Angeles,Manufacturing,1
17,42954,18,185,Exusia,exusia,New York,NY,New York,8803.2659,14917600,9.0,8,New York City,IT Services,1
18,42955,19,35,Thrive Farmers,thrive-farmers,Georgia,GA,Roswell,8577.1781,23181949,29.0,11,Atlanta,Food & Beverage,1
19,42956,20,10,Tribeca Marketing Group,tribeca-marketing-group,Florida,FL,Hollywood,8395.2895,8629685,1.0,19,Miami,Education,1
20,36809,21,15,C&H Financial Services,ch-financial-services,Illinois,IL,Westchester,8052.9041,17349869,17.0,2,Chicago,Financial Services,2
21,42957,22,6,PAYKINGS,paykings,Florida,FL,Apollo Beach,7905.4255,8099089,7.0,2,Tampa,Financial Services,1
22,42958,23,5,Highland Project Logistics,highland-project-logistics,New Hampshire,NH,Londonderry,7903.5540,8003634,6.0,6,Boston,Logistics & Transportation,1
23,42959,24,8,Furniture Solutions Group,furniture-solutions-group,Maryland,MD,Annapolis,7799.5978,8623201,35.0,17,Baltimore,Business Products & Services,1
24,37267,25,200,Midwest Equity Mortgage,midwest-equity-mortgage,Illinois,IL,Oakbrook,7754.3956,971148423,17.0,2,Chicago,Financial Services,2
25,42960,26,16,Big Block Realty,big-block-realty,California,CA,San Diego,7612.7068,19031027,11.0,3,San Diego,Real Estate,1
26,44578,26,235,Cylance,cylance,California,CA,Irvine,7613.0469,11100000,2.0,13,Los Angeles,Security,1
27,42961,27,30,Blackstone Labs,blackstone-labs,Florida,FL,Boca Raton,7546.0566,9718979,1.0,10,Miami,Health,1
28,42962,28,25,Elements Holdings Group Inc & Subsidiaries,elements-holdings-group-inc-subsidiaries,Illinois,IL,Chicago,7117.1678,18557648,17.0,17,Chicago,Business Products & Services,1
29,42963,29,140,Legend Solar,legend-solar,Utah,UT,Washington,7101.8827,13005808,308.0,16,"St. George, UT",Energy,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4972,44569,4971,57,Nexgrill Industries,nexgrill-industries,California,CA,Chino,41.1087,125672898,54.0,4,"Riverside-San Bernardino-Ontario, CA",Consumer Products & Services,1
4973,24399,4972,72,US-Analytics Solutions Group,us-analytics-solutions-group,Texas,TX,Irving,41.0782,17900000,8.0,17,Dallas,Business Products & Services,4
4974,3932,4973,131,Saturn Freight Systems,saturn-freight-systems,Georgia,GA,MARIETTA,40.9159,41548751,29.0,6,Atlanta,Logistics & Transportation,7
4975,18517,4974,250,Central Welding Supply,central-welding-supply,Washington,WA,N Lakewood,40.8664,75574615,23.0,17,Seattle,Business Products & Services,3
4976,4025,4975,553,PLS Logistics Services,pls-logistics-services,Pennsylvania,PA,Cranberry Township,40.7902,529623000,52.0,6,"Pittsburgh, PA",Logistics & Transportation,3
4977,44570,4976,13,Klingman & Associates,klingman-associates,New York,NY,New York,40.7156,7208754,9.0,2,New York City,Financial Services,1
4978,44571,4977,54,CivicSource,civicsource,Louisiana,LA,New Orleans,40.7194,12000809,1010.0,7,"New Orleans-Metairie, LA",Government Services,1
4979,23072,4978,25,3 Key Elements,3-key-elements,Utah,UT,South Jordan,40.7080,2930244,12.0,19,Salt Lake City,Education,4
4980,44572,4979,121,Justice AV Solutions,justice-av-solutions,Kentucky,KY,Louisville,40.7100,20042109,630.0,15,"Louisville/Jefferson County, KY-IN",Manufacturing,1
4981,3756,4980,98,OMNI Systems,omni-systems,Ohio,OH,Richmond Heights,40.6613,50451607,79.0,15,Cleveland,Manufacturing,6
4982,38185,4981,54,Dynamic Edge,dynamic-edge,Michigan,MI,Ann Arbor,40.6594,4656600,84.0,8,"Ann Arbor, MI",IT Services,2
4983,4180,4982,21,Cases By Source,cases-by-source,New Jersey,NJ,Mahwah,40.6337,8918190,9.0,15,New York City,Manufacturing,6
4984,37213,4983,7,Darren James Real Estate Experts,darren-james-real-estate-experts,Louisiana,LA,Denham Springs,40.5998,2197996,139.0,3,"Baton Rouge, LA",Real Estate,2
4985,25574,4984,29,Hawkins International Public Relations,hawkins-international-public-relations,New York,NY,New York,40.5837,4105744,9.0,22,New York City,Travel & Hospitality,3
4986,888,4985,481,Liquid Web,liquid-web,Michigan,MI,Lansing,40.4646,69603000,144.0,8,"Lansing-East Lansing, MI",IT Services,10
4987,11627,4986,260,NewAgeSys,newagesys,New Jersey,NJ,Princeton Junction,40.4367,17851875,1012.0,8,"Trenton, NJ",IT Services,8
4988,44573,4987,26,Blue Ocean Pharma,blue-ocean-pharma,New Jersey,NJ,Annandale,40.4126,5309000,9.0,5,New York City,Advertising & Marketing,1
4989,44574,4988,30,Tenaglia & Hunt,tenaglia-hunt,New Jersey,NJ,Rochelle Park,40.3884,3520611,9.0,17,New York City,Business Products & Services,1
4990,44575,4989,12,Lenny & Eva,lenny-eva,Tennessee,TN,Cookeville,40.3680,5462004,613.0,4,"Cookeville, TN",Consumer Products & Services,1
4991,20473,4990,2323,Accurate Home Care,accurate-home-care,Minnesota,MN,Otsego,40.2554,58817000,13.0,10,Minneapolis,Health,6
4992,44576,4991,135,Digital Marketer,digital-marketer,Texas,TX,Austin,40.2551,14071111,18.0,5,Austin,Advertising & Marketing,1
4993,8160,4992,9,Sperry Van Ness International,sperry-van-ness-international,Massachusetts,MA,Boston,40.2060,6807000,6.0,3,Boston,Real Estate,3
4994,1821,4993,51,LetterLogic,letterlogic,Tennessee,TN,Nashville,40.1270,35373305,82.0,17,Nashville,Business Products & Services,10
4995,19049,4994,303,Fenwick & West,fenwick-west,California,CA,Mountain View,40.0771,363500000,20.0,17,San Jose,Business Products & Services,5
4996,44577,4995,104,Stonehaven Dental,stonehaven-dental,Utah,UT,Lehi,40.0760,10755433,48.0,10,"Provo-Orem, UT",Health,1
4997,4114,4996,105,Duffey Petrosky,duffey-petrosky,Michigan,MI,Farmington Hills,40.0476,15233132,50.0,5,Detroit,Advertising & Marketing,8
4998,20674,4997,22,Southridge Technology Grp,southridge-technology-grp,Connecticut,CT,Brookfield,39.8074,3713531,58.0,8,"Bridgeport-Stamford-Norwalk, CT",IT Services,6
4999,23258,4998,1951,Stratosphere Quality,stratosphere-quality,Indiana,IN,Fishers,39.7451,102252325,81.0,15,"Indianapolis, IN",Manufacturing,4
5000,9017,4999,278,Optimax Systems,optimax-systems,New York,NY,Ontario,39.7253,27989715,71.0,15,"Rochester, NY",Manufacturing,5
5001,24552,5000,277,Murray Resources,murray-resources,Texas,TX,Houston,39.7237,5714518,22.0,21,Houston,Human Resources,3

In [274]:
inc2016_df = inc2016_df.rename(columns={"id":"ID", "rank":"Rank", "workers":"Employees", "company":"Company2016",
                                       "url":"Website", "city":"City", "revenue": "Revenue",
                                       "yrs_on_list":"Years On List", "state_l":"State"})
inc2016_df = inc2016_df.drop(columns={"growth", "ifmid", "ifiid", "metro", "industry","state_s"})
inc2016_df.columns

Index(['ID', 'Rank', 'Employees', 'Company2016', 'Website', 'State', 'City',
       'Revenue', 'Years On List'],
      dtype='object')

In [275]:
inc2016_df.head()

,ID,Rank,Employees,Company2016,Website,State,City,Revenue,Years On List
0,42940,1,218,Loot Crate,loot-crate,California,Los Angeles,116247698,1
1,42941,2,100,Paint Nite,paint-nite,Massachusetts,Somerville,55018793,1
2,42942,3,47,CalCom Solar,calcom-solar,California,Visalia,33507450,1
3,36643,4,82,eLuxurySupply.com,eluxurysupplycom,Indiana,Evansville,30695215,2
4,36639,5,48,Company.com,companycom,Georgia,Atlanta,33370967,2

In [276]:
inc2018_file = "./Resources/inc5000-2018.csv"
inc2018_df = pd.read_csv(inc2018_file)
inc2018_df.dropna(axis=1, how='all')

,_ - id,_ - url,_ - rank,_ - city,_ - ifmid,_ - ifiid,_ - growth,_ - workers,_ - company,_ - website,...,_ - zipcode,_ - founded,_ - industry,_ - latitude,_ - metrocode,_ - longitude,_ - yrs_on_list,_ - previous_workers,_ - metro,_ - partner_lists - partner_lists
0,71021.0,swanleap,1.0,Madison,78.0,6.0,75660.8425,49.0,SwanLeap,http://swanleap.com,...,53719.0,2013.0,Logistics & Transportation,43.04531,"Madison, WI",-89.51538,2.0,4.0,"Madison, WI",NaN
1,87397.0,popsockets,2.0,Boulder,31.0,4.0,71423.7620,118.0,PopSockets,http://popsockets.com,...,80301.0,2010.0,Consumer Products & Services,40.04947,"Boulder, CO",-105.20142,1.0,2.0,"Boulder, CO",NaN
2,87398.0,home-chef,3.0,Chicago,17.0,11.0,60165.5058,865.0,Home Chef,homechef.com,...,60611.0,2013.0,Food & Beverage,41.89570,"Chicago-Naperville-Elgin, IL-IN-WI",-87.61378,1.0,35.0,Chicago,NaN
3,81957.0,velocity-global,4.0,Denver,30.0,17.0,39816.5093,55.0,Velocity Global,http://velocityglobal.com,...,80205.0,2013.0,Business Products & Services,39.75886,"Denver-Aurora-Lakewood, CO",-104.96283,1.0,1.0,Denver,NaN
4,87399.0,depcom-power,5.0,Scottsdale,46.0,16.0,38962.9022,104.0,DEPCOM Power,depcompower.com,...,85258.0,2013.0,Energy,33.56430,"Phoenix-Mesa-Scottsdale, AZ",-111.89588,1.0,27.0,Phoenix,NaN
5,87400.0,aeronux-airways,6.0,Marietta,29.0,6.0,20005.2390,17.0,Aeronux Airways,aeronux.com,...,30066.0,2011.0,Logistics & Transportation,34.03239,"Atlanta-Sandy Springs-Roswell, GA",-84.50515,1.0,3.0,Atlanta,NaN
6,87401.0,diamond-assets,7.0,Milton,171.0,25.0,19717.5129,41.0,Diamond Assets,diamond-assets.com,...,53563.0,2014.0,Computer Hardware,42.80449,"Janesville, WI",-88.91599,1.0,2.0,NaN,NaN
7,87402.0,gforce-life-sciences,8.0,Chicago,17.0,21.0,16426.6575,13.0,GForce Life Sciences,http://gforcestaff.com,...,60606.0,2013.0,Human Resources,41.88207,"Chicago-Naperville-Elgin, IL-IN-WI",-87.63735,1.0,3.0,Chicago,NaN
8,86959.0,flexport,8.0,San Francisco,4.0,6.0,15911.2237,532.0,Flexport,http://flexport.com,...,94102.0,2013.0,Logistics & Transportation,37.77959,"San Francisco-Oakland-Hayward, CA",-122.41932,1.0,26.0,San Francisco,NaN
9,69341.0,scientistcom,9.0,Solana Beach,11.0,10.0,15267.7557,49.0,Scientist.com,http://scientist.com,...,92075.0,2007.0,Health,32.99725,"San Diego-Carlsbad, CA",-117.26058,2.0,8.0,San Diego,NaN
10,43343.0,the-garrett-companies,10.0,Greenwood,81.0,3.0,14821.8995,40.0,The Garrett Companies,http://thegarrettco.com,...,46143.0,2014.0,Real Estate,39.59586,"Indianapolis-Carmel-Anderson, IN",-86.11632,3.0,6.0,"Indianapolis, IN",NaN
11,70931.0,dgc-international,11.0,Vienna,3.0,7.0,14475.5148,55.0,DGC International,dgci.com,...,22182.0,2010.0,Government Services,38.93842,"Washington-Arlington-Alexandria, DC-VA-MD-WV",-77.27552,2.0,4.0,"Washington, DC",NaN
12,87403.0,exabeam,12.0,San Mateo,4.0,13.0,14032.4773,153.0,Exabeam,exabeam.com,...,94403.0,2013.0,Security,37.53845,"San Francisco-Oakland-Hayward, CA",-122.30545,1.0,22.0,San Francisco,NaN
13,87000.0,podium,13.0,Lehi,48.0,17.0,13645.2287,254.0,Podium,podium.com,...,84043.0,2013.0,Business Products & Services,40.41076,"Provo-Orem, UT",-111.87679,1.0,5.0,"Provo-Orem, UT",NaN
14,87404.0,inova-us,14.0,Key Biscayne,1.0,5.0,13135.1845,25.0,Inova US,inovaus.com,...,33149.0,2008.0,Advertising & Marketing,25.71951,"Miami-Fort Lauderdale-West Palm Beach, FL",-80.16854,1.0,12.0,Miami,NaN
15,87405.0,adrizer,15.0,Sarasota,576.0,9.0,12500.7218,24.0,AdRizer,adrizer.com,...,34236.0,2013.0,Software,27.31649,"Sarasota-Bradenton-Venice, FL",-82.55353,1.0,2.0,"Sarasota-Bradenton-Venice, FL",NaN
16,87406.0,welfont,16.0,Tampa,7.0,3.0,11359.3104,55.0,Welfont,welfont.com,...,33602.0,2014.0,Real Estate,27.95353,"Tampa-St. Petersburg-Clearwater, FL",-82.45711,1.0,1.0,Tampa,NaN
17,67751.0,thinx,17.0,New York City,9.0,18.0,10924.1379,44.0,THINX,shethinx.com,...,10001.0,2014.0,Retail,40.75063,"New York-Newark-Jersey City, NY-NJ-PA",-73.99718,1.0,4.0,New York City,NaN
18,71141.0,draken-international,18.0,Lakeland,575.0,7.0,10562.3592,200.0,Draken International,drakenintl.com,...,33811.0,2011.0,Government Services,27.98440,"Lakeland, FL",-82.01526,2.0,50.0,NaN,NaN
19,87407.0,calmcom,19.0,San Francisco,4.0,4.0,10548.7682,25.0,Calm.com,calm.com,...,94105.0,2012.0,Consumer Products & Services,37.78986,"San Francisco-Oakland-Hayward, CA",-122.39366,1.0,3.0,San Francisco,NaN
20,87408.0,curate-partners,20.0,Stoneham,6.0,21.0,10056.5729,13.0,Curate Partners,curatepartners.com,...,2180.0,2014.0,Human Resources,42.47421,"Boston-Cambridge-Newton, MA-NH",-71.09767,1.0,7.0,Boston,NaN
21,87409.0,figs,21.0,Los Angeles,2.0,18.0,9947.5655,45.0,FIGS,wearfigs.com,...,90064.0,2013.0,Retail,34.03725,"Los Angeles-Long Beach-Anaheim, CA",-118.42357,1.0,2.0,Los Angeles,NaN
22,70956.0,techanax,22.0,Woodbridge,3.0,7.0,9508.0119,20.0,TechAnax,techanax.com,...,22193.0,2012.0,Government Services,38.64420,"Washington-Arlington-Alexandria, DC-VA-MD-WV",-77.35200,2.0,4.0,"Washington, DC",NaN
23,87017.0,snacknation,24.0,Culver City,2.0,11.0,9199.5777,158.0,SnackNation,snacknation.com,...,90232.0,2014.0,Food & Beverage,34.01932,"Los Angeles-Long Beach-Anaheim, CA",-118.39190,1.0,5.0,Los Angeles,NaN
24,87410.0,brooklinen,25.0,Brooklyn,9.0,18.0,9154.1993,22.0,Brooklinen,brooklinen.com,...,11201.0,2014.0,Retail,40.69368,"New York-Newark-Jersey City, NY-NJ-PA",-73.98969,1.0,2.0,New York City,NaN
25,87411.0,lo70s,26.0,Henderson,1004.0,5.0,9153.7815,9.0,Lo70s,lo70s.com,...,89015.0,2013.0,Advertising & Marketing,36.03931,"Las Vegas-Henderson-Paradise, NV",-114.92803,1.0,2.0,"Las Vegas, NV",NaN
26,87412.0,funded-today,27.0,South Ogden,204.0,5.0,8797.7051,55.0,Funded Today,funded.today.com,...,84403.0,2014.0,Advertising & Marketing,41.21499,"Ogden-Clearfield, UT",-111.88959,1.0,3.0,"Ogden-Clearfield, UT",NaN
27,87413.0,progyny,28.0,New York City,9.0,10.0,8675.3088,89.0,Progyny,progyny.com,...,10016.0,2008.0,Health,40.74522,"New York-Newark-Jersey City, NY-NJ-PA",-73.97830,1.0,66.0,New York City,NaN
28,87414.0,shipmonk,29.0,Deerfield Beach,1.0,6.0,7636.3561,85.0,ShipMonk,shipmonk.com,...,33441.0,2014.0,Logistics & Transportation,26.31110,"Miami-Fort Lauderdale-West Palm Beach, FL",-80.09787,1.0,3.0,Miami,EO
29,87415.0,powerinbox,30.0,New York City,9.0,9.0,7534.2742,40.0,PowerInbox,powerinbox.com,...,10036.0,2012.0,Software,40.75926,"New York-Newark-Jersey City, NY-NJ-PA",-73.98986,1.0,18.0,New York City,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4983,26562.0,pacific-western-painting,4971.0,Escondido,11.0,20.0,58.2372,52.0,Pacific Western Painting,pacwestpainting.com,...,92025.0,2005.0,Construction,33.10200,"San Diego-Carlsbad, CA",-117.08042,5.0,47.0,San Diego,NaN
4984,36662.0,muscle-up-marketing,4972.0,Alpharetta,29.0,5.0,58.1952,13.0,Muscle Up Marketing,muscleupmarketing.com,...,30009.0,2011.0,Advertising & Marketing,34.07910,"Atlanta-Sandy Springs-Roswell, GA",-84.30526,4.0,8.0,Atlanta,NaN
4985,787.0,insight-global,4973.0,Atlanta,29.0,17.0,58.1746,2570.0,Insight Global,insightglobal.com,...,30319.0,2001.0,Business Products & Services,33.87595,"Atlanta-Sandy Springs-Roswell, GA",-84.33476,11.0,1645.0,Atlanta,NaN
4986,25676.0,ideascale,4974.0,San Francisco,4.0,9.0,58.1719,25.0,IdeaScale,ideascale.com,...,94104.0,2009.0,Software,37.79141,"San Francisco-Oakland-Hayward, CA",-122.40213,4.0,20.0,San Francisco,NaN
4987,79556.0,amiano-son-construction,4975.0,Tabernacle,49.0,20.0,58.1734,13.0,Amiano & Son Construction,amianoandson.com,...,8088.0,2000.0,Construction,39.85147,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",-74.69341,1.0,10.0,Philadelphia,NaN
4988,37145.0,intellectual-capitol,4976.0,Greenville,107.0,29.0,58.0966,23.0,Intellectual Capitol,icapsolutions.net,...,29607.0,2003.0,IT System Development,34.81279,"Greenville-Mauldin-Easley, SC",-82.33171,4.0,9.0,"Greenville-Mauldin-Easley, SC",NaN
4989,18527.0,citrin-cooperman,4977.0,New York City,9.0,2.0,58.0851,898.0,Citrin Cooperman,citrincooperman.com,...,10017.0,1979.0,Financial Services,40.75236,"New York-Newark-Jersey City, NY-NJ-PA",-73.97249,2.0,556.0,New York City,NaN
4990,18424.0,mobile-one-courier,4978.0,Virginia Beach,15.0,6.0,58.0631,110.0,Mobile One Courier,mobileonecourier.com,...,23692.0,1996.0,Logistics & Transportation,37.19244,"Virginia Beach-Norfolk-Newport News, VA-NC",-76.46358,6.0,85.0,Virginia Beach,Vistage
4991,25069.0,mediassociates,4979.0,Sandy Hook,58.0,5.0,58.0446,0.0,Mediassociates,mediassociates.com,...,6482.0,1996.0,Advertising & Marketing,41.40814,"Bridgeport-Stamford-Norwalk, CT",-73.24249,4.0,0.0,"Bridgeport-Stamford-Norwalk, CT",NaN
4992,89214.0,site-worx,4980.0,Lebanon,47.0,20.0,57.9816,115.0,Site WORX,swxohio.com,...,45036.0,2010.0,Construction,39.44405,"Cincinnati, OH-KY-IN",-84.21413,1.0,74.0,Cincinnati,NaN
4993,36668.0,entrust-energy,4981.0,Houston,22.0,16.0,57.9385,155.0,Entrust Energy,entrustenergy.com,...,77010.0,2010.0,Energy,29.75362,"Houston-The Woodlands-Sugar Land, TX",-95.35981,4.0,123.0,Houston,NaN
4994,89215.0,appliance-world-of-huntington,4982.0,Huntington,9.0,18.0,57.9154,54.0,Appliance World of Huntington,applianceworld.com,...,11743.0,1992.0,Retail,40.88341,"New York-Newark-Jersey City, NY-NJ-PA",-73.42356,1.0,48.0,New York City,NaN
4995,11729.0,enscicon,4983.0,Denver,30.0,24.0,57.8537,166.0,Enscicon,enscicon.com,...,80211.0,1994.0,Engineering,39.76744,"Denver-Aurora-Lakewood, CO",-105.01974,2.0,150.0,Denver,NaN
4996,38005.0,energy-fitness,4984.0,St James,9.0,10.0,57.8230,140.0,Energy Fitness,energyfitness.com,...,11780.0,2003.0,Health,40.90929,"New York-Newark-Jersey City, NY-NJ-PA",-73.17473,3.0,80.0,New York City,NaN
4997,43582.0,targetrecruit,4985.0,Nashville,4.0,29.0,57.7913,53.0,TargetRecruit,targetrecruit.net,...,94566.0,2008.0,IT System Development,37.64810,"San Francisco-Oakland-Hayward, CA",-121.84996,2.0,38.0,San Francisco,NaN
4998,89216.0,welligent,4986.0,Norfolk,15.0,9.0,57.6996,28.0,Welligent,welligent.com,...,23508.0,2001.0,Software,36.88489,"Virginia Beach-Norfolk-Newport News, VA-NC",-76.31027,1.0,21.0,Virginia Beach,NaN
4999,3813.0,pacific-dental-services,4987.0,Irvine,2.0,10.0,57.6902,9008.0,Pacific Dental Services,pacificdentalservices.com,...,92614.0,1994.0,Health,33.68030,"Los Angeles-Long Beach-Anaheim, CA",-117.83330,13.0,5961.0,Los Angeles,NaN
5000,23916.0,nina-hale,4988.0,Minneapolis,13.0,5.0,57.6482,66.0,Nina Hale,ninahale.com,...,55402.0,2005.0,Advertising & Marketing,44.97604,"Minneapolis-St. Paul-Bloomington, MN-WI",-93.27144,6.0,26.0,Minneapolis,NaN
5001,87374.0,tazikis-mediterranean-cafe,4989.0,Birmingham,140.0,11.0,57.6074,386.0,Taziki's Mediterranean Cafe,tazikiscafe.com,...,35242.0,1997.0,Food & Beverage,33.42525,"Birmingham-Hoover, AL",-86.67208,1.0,252.0,"Birmingham, AL",NaN
5002,43848.0,advanced-strategic-enterprise-concepts-3,4990.0,Reston,3.0,7.0,57.6022,35.0,Advanced Strategic Enterprise Concepts 3,asec3.com,...,20191.0,2012.0,Government Services,38.93465,"Washington-Arlington-Alexandria, DC-VA-MD-WV",-77.35170,3.0,25.0,"Washington, DC",NaN
5003,43124.0,shop-melee,4991.0,Willowbrook,17.0,4.0,57.5653,39.0,SHOP MELEE,shopmelee.com,...,60527.0,2012.0,Consumer Products & Services,41.74307,"Chicago-Naperville-Elgin, IL-IN-WI",-87.92921,3.0,31.0,Chicago,NaN
5004,89217.0,pacific-alliance-capital,4992.0,Aliso Vijeo,2.0,25.0,57.4304,12.0,Pacific Alliance Capital,pacificalliancecapital.com,...,92656.0,2000.0,Computer Hardware,33.57621,"Los Angeles-Long Beach-Anaheim, CA",-117.73037,1.0,8.0,Los Angeles,NaN
5005,37945.0,touchsource,4993.0,Lafayette,31.0,17.0,57.4114,34.0,TouchSource,touchsource.com,...,80026.0,1985.0,Business Products & Services,40.01225,"Boulder, CO",-105.09976,4.0,17.0,"Boulder, CO",NaN
5006,89218.0,flow-right-plumbing-heating-irrigation,4994.0,Pueblo,896.0,20.0,57.4060,47.0,"Flow Right Plumbing, Heating, & Irrigation",flowrightphi.com,...,81003.0,2008.0,Construction,38.27959,"Pueblo, CO",-104.63146,1.0,20.0,NaN,NaN
5007,44124.0,accela,4995.0,San Ramon,4.0,7.0,57.3917,427.0,Accela,accela.com,...,94583.0,1999.0,Government Services,37.75512,"San Francisco-Oakland-Hayward, CA",-121.97270,3.0,431.0,San Francisco,NaN
5008,19023.0,pentec-health,4996.0,Glen Mills,49.0,10.0,57.3485,580.0,Pentec Health,pentechealth.com,...,19342.0,1983.0,Health,39.90412,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",-75.49942,9.0,378.0,Philadelphia,NaN
5009,74151.0,progressive-freight,4997.0,Thomasville,562.0,6.0,57.3364,12.0,Progressive Freight,progressivefreight.com,...,31799.0,2003.0,Logistics & Transportation,30.84100,"Thomasville, GA",-83.98350,2.0,8.0,NaN,NaN
5010,4284.0,traffic-planning-and-design,4998.0,Pottstown,49.0,24.0,57.2994,160.0,"Traffic Planning and Design, Inc.",trafficpd.com,...,19464.0,1989.0,Engineering,40.25893,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",-75.61586,4.0,107.0,Philadelphia,NaN
5011,22257.0,weld-power-generator,4999.0,Millbury,113.0,16.0,57.2794,38.0,Weld Power Generator,weldpower.com,...,1527.0,1951.0,Energy,42.19225,"Worcester, MA",-71.77765,6.0,20.0,NaN,NaN
5012,21993.0,pedigree-technologies,5000.0,Fargo,118.0,9.0,57.2358,69.0,Pedigree Technologies,pedigreetechnologies.com,...,58104.0,2004.0,Software,46.79323,"Fargo, ND-MN",-96.83968,7.0,64.0,NaN,NaN

In [277]:
inc2018_df = inc2018_df.rename(columns={"_ - id":"ID", "_ - rank":"Rank", "_ - company":"Company2018",
                                       "_ - url":"Website", "_ - city":"City", "_ - revenue": "Revenue",
                                       "_ - yrs_on_list":"Years On List", "_ - workers":"Employees","_ - state_l":"State"})
inc2018_df = inc2018_df.drop(columns={"_ - industry", "_ - ifmid", "_ - ifiid", "_ - website", "_ - zipcode", "_ - founded",
                                     "_ - state_s", "_ - latitude", "_ - metrocode", "_ - longitude", "_ - previous_workers", 
                                     "_ - metro", "_ - partner_lists - partner_lists", "_ - growth"})
inc2018_df.columns

Index(['ID', 'Website', 'Rank', 'City', 'Employees', 'Company2018', 'State',
       'Revenue', 'Years On List'],
      dtype='object')

In [278]:
inc2018_df.head()

,ID,Website,Rank,City,Employees,Company2018,State,Revenue,Years On List
0,71021.0,swanleap,1.0,Madison,49.0,SwanLeap,Wisconsin,98965631.0,2.0
1,87397.0,popsockets,2.0,Boulder,118.0,PopSockets,Colorado,168837562.0,1.0
2,87398.0,home-chef,3.0,Chicago,865.0,Home Chef,Illinois,255047839.0,1.0
3,81957.0,velocity-global,4.0,Denver,55.0,Velocity Global,Colorado,49175942.0,1.0
4,87399.0,depcom-power,5.0,Scottsdale,104.0,DEPCOM Power,Arizona,219574136.0,1.0

In [298]:
inc2016_cols = ["ID", "Company2016", "Rank", "Revenue"]
inc2016_transformed= inc2016_df[inc2016_cols].copy()

inc2016_transformed.drop_duplicates("ID", inplace=True)
inc2016_transformed.set_index("ID", inplace=True)

inc2016_transformed.head()

             Company2016  Rank    Revenue
ID
42940         Loot Crate     1  116247698
42941         Paint Nite     2   55018793
42942       CalCom Solar     3   33507450
36643  eLuxurySupply.com     4   30695215
36639        Company.com     5   33370967

In [300]:
inc2018_cols = ["ID", "Rank", "Company2018", "Revenue"]
inc2018_transformed= inc2018_df[inc2018_cols].copy()

inc2018_transformed.drop_duplicates("ID", inplace=True)
inc2018_transformed.set_index("ID", inplace=True)

inc2018_transformed.head()

         Rank      Company2018      Revenue
ID
71021.0   1.0         SwanLeap   98965631.0
87397.0   2.0       PopSockets  168837562.0
87398.0   3.0        Home Chef  255047839.0
81957.0   4.0  Velocity Global   49175942.0
87399.0   5.0     DEPCOM Power  219574136.0

In [303]:
connection_string = "root:@localhost/ETL_Project"
engine = create_engine(f'mysql://{connection_string}')

In [316]:
# Confirm tables
engine.table_names()

['inc2016', 'inc2016info', 'inc2018']

In [317]:
inc2016_transformed.to_sql(name='inc2016', con=engine, if_exists='append', index=True, 'utf-8', 'replace')

SyntaxError: positional argument follows keyword argument (<ipython-input-317-181ac3b2ac4c>, line 1)

In [318]:
inc2018_transformed.to_sql(name='inc2018', con=engine, if_exists='append', index=True)

IntegrityError: (pymysql.err.IntegrityError) (1048, "Column 'ID' cannot be null") [SQL: 'INSERT INTO inc2018 (`ID`, `Rank`, `Company2018`, `Revenue`) VALUES (%(ID)s, %(Rank)s, %(Company2018)s, %(Revenue)s)'] [parameters: ({'ID': 71021.0, 'Rank': 1.0, 'Company2018': 'SwanLeap', 'Revenue': 98965631.0}, {'ID': 87397.0, 'Rank': 2.0, 'Company2018': 'PopSockets', 'Revenue': 168837562.0}, {'ID': 87398.0, 'Rank': 3.0, 'Company2018': 'Home Chef', 'Revenue': 255047839.0}, {'ID': 81957.0, 'Rank': 4.0, 'Company2018': 'Velocity Global', 'Revenue': 49175942.0}, {'ID': 87399.0, 'Rank': 5.0, 'Company2018': 'DEPCOM Power', 'Revenue': 219574136.0}, {'ID': 87400.0, 'Rank': 6.0, 'Company2018': 'Aeronux Airways', 'Revenue': 21874500.0}, {'ID': 87401.0, 'Rank': 7.0, 'Company2018': 'Diamond Assets', 'Revenue': 43084462.0}, {'ID': 87402.0, 'Rank': 8.0, 'Company2018': 'GForce Life Sciences', 'Revenue': 16893384.0}  ... displaying 10 of 5001 total bound parameter sets ...  {'ID': 22257.0, 'Rank': 4999.0, 'Company2018': 'Weld Power Generator', 'Revenue': 6570866.0}, {'ID': 21993.0, 'Rank': 5000.0, 'Company2018': 'Pedigree Technologies', 'Revenue': 14266000.0})] (Background on this error at: http://sqlalche.me/e/gkpj)

In [321]:
inc2016_2018 = pd.merge(inc2016_df, inc2018_df, on="ID", how="left")

In [326]:
inc2016_2018 = inc2016_2018.rename(columns={"Rank_x":"Rank2016", "Employees_x":"Employees2016", "Website_x":"Website2016",
                                           "State_x":"State2016", "City_x":"City2016", "Revenue_x":"Revenue2016",
                                           "Years On List_x":"Years On List2016", "Website_y":"Website 2018",
                                           "Rank_y":"Rank2018", "City_y":"City2018", "Employees_y":"Employees2018",
                                           "State_y":"State2018", "Revenue_y":"Revenue2018", "Years On List_y":"Years On List 2018"})
inc2016_2018

,ID,Rank2016,Employees2016,Company2016,Website2016,State2016,City2016,Revenue2016,Years On List2016,Website 2018,Rank 2018,City2018,Employees2018,Company2018,State2018,Revenue 2018,Years On List 2018
0,42940,1,218,Loot Crate,loot-crate,California,Los Angeles,116247698,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,42941,2,100,Paint Nite,paint-nite,Massachusetts,Somerville,55018793,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,42942,3,47,CalCom Solar,calcom-solar,California,Visalia,33507450,1,california-commerical-solar,783.0,Visalia,72.0,California Commerical Solar,California,49422404.0,3.0
3,36643,4,82,eLuxurySupply.com,eluxurysupplycom,Indiana,Evansville,30695215,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,36639,5,48,Company.com,companycom,Georgia,Atlanta,33370967,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,42943,6,15,Globalization Partners,globalization-partners,Massachusetts,Cambridge,17743829,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,42944,7,130,Bounce Exchange,bounce-exchange,New York,New York,15733570,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,42945,8,25,Los York,los-york,California,Santa Monica,15598837,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,42946,9,39,PANTHERx Specialty Pharmacy,pantherx-specialty-pharmacy,Pennsylvania,Pittsburgh,42425003,1,pantherx-specialty-pharmacy,49.0,Pittsburgh,92.0,PANTHERx Specialty Pharmacy,Pennsylvania,454329217.0,3.0
9,42947,10,9,FedBiz IT Solutions,fedbiz-it-solutions,Virginia,Leesburg,25863238,1,fedbiz-it-solutions,116.0,Leesburg,9.0,"FedBiz IT Solutions, LLC",Virginia,20071682.0,3.0
10,42948,11,14,Small Business Owners of America,small-business-owners-of-america,Ohio,Columbus,12369863,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,42949,12,52,PLANIT GROUP,planit-group,North Carolina,Charlotte,11518066,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,42950,13,250,Suja Juice,suja-juice,California,San Diego,65877327,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,42951,14,105,S2 Capital,s2-capital,Texas,Addison,28804779,1,s2-capital,702.0,Addison,260.0,S2 Capital,Texas,91675000.0,3.0
14,37197,15,35,FormulaFolio Investments,formulafolio-investments,Michigan,Grand Rapids,11212596,2,formulafolio-investments,385.0,Grand Rapids,61.0,FormulaFolio Investments,Michigan,29255727.0,4.0
15,42952,16,171,Persado,persado,New York,New York,17432811,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,42953,17,15,Berkley,berkley,California,Carson,11449478,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,42954,18,185,Exusia,exusia,New York,New York,14917600,1,exusia,1678.0,New York City,366.0,Exusia,New York,26135931.0,3.0
18,42955,19,35,Thrive Farmers,thrive-farmers,Georgia,Roswell,23181949,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,42956,20,10,Tribeca Marketing Group,tribeca-marketing-group,Florida,Hollywood,8629685,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,36809,21,15,C&H Financial Services,ch-financial-services,Illinois,Westchester,17349869,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,42957,22,6,PAYKINGS,paykings,Florida,Apollo Beach,8099089,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,42958,23,5,Highland Project Logistics,highland-project-logistics,New Hampshire,Londonderry,8003634,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,42959,24,8,Furniture Solutions Group,furniture-solutions-group,Maryland,Annapolis,8623201,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,37267,25,200,Midwest Equity Mortgage,midwest-equity-mortgage,Illinois,Oakbrook,971148423,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,42960,26,16,Big Block Realty,big-block-realty,California,San Diego,19031027,1,big-block-realty,33.0,San Diego,15.0,Big Block Realty,California,47786549.0,3.0
26,44578,26,235,Cylance,cylance,California,Irvine,11100000,1,cylance,171.0,Irvine,844.0,Cylance,California,108751669.0,3.0
27,42961,27,30,Blackstone Labs,blackstone-labs,Florida,Boca Raton,9718979,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,42962,28,25,Elements Holdings Group Inc & Subsidiaries,elements-holdings-group-inc-subsidiaries,Illinois,Chicago,18557648,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,42963,29,140,Legend Solar,legend-solar,Utah,Washington,13005808,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4972,44569,4971,57,Nexgrill Industries,nexgrill-industries,California,Chino,125672898,1,nexgrill-industries,2209.0,Chino,72.0,Nexgrill Industries,California,187181361.0,3.0
4973,24399,4972,72,US-Analytics Solutions Group,us-analytics-solutions-group,Texas,Irving,17900000,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4974,3932,4973,131,Saturn Freight Systems,saturn-freight-systems,Georgia,MARIETTA,41548751,7,saturn-freight-systems,4664.0,Marietta,157.0,Saturn Freight Systems,Georgia,61325816.0,8.0
4975,18517,4974,250,Central Welding Supply,central-welding-supply,Washington,N Lakewood,75574615,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4976,4025,4975,553,PLS Logistics Services,pls-logistics-services,Pennsylvania,Cranberry Township,529623000,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4977,44570,4976,13,Klingman & Associates,klingman-associates,New York,New York,7208754,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4978,44571,4977,54,CivicSource,civicsource,Louisiana,New Orleans,12000809,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4979,23072,4978,25,3 Key Elements,3-key-elements,Utah,South Jordan,2930244,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4980,44572,4979,121,Justice AV Solutions,justice-av-solutions,Kentucky,Louisville,20042109,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4981,3756,4980,98,OMNI Systems,omni-systems,Ohio,Richmond Heights,50451607,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4982,38185,4981,54,Dynamic Edge,dynamic-edge,Michigan,Ann Arbor,4656600,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4983,4180,4982,21,Cases By Source,cases-by-source,New Jersey,Mahwah,8918190,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4984,37213,4983,7,Darren James Real Estate Experts,darren-james-real-estate-experts,Louisiana,Denham Springs,2197996,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4985,25574,4984,29,Hawkins International Public Relations,hawkins-international-public-relations,New York,New York,4105744,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4986,888,4985,481,Liquid Web,liquid-web,Michigan,Lansing,69603000,10,liquid-web,4845.0,Lansing,591.0,Liquid Web,Michigan,105986240.0,11.0
4987,11627,4986,260,NewAgeSys,newagesys,New Jersey,Princeton Junction,17851875,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4988,44573,4987,26,Blue Ocean Pharma,blue-ocean-pharma,New Jersey,Annandale,5309000,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4989,44574,4988,30,Tenaglia & Hunt,tenaglia-hunt,New Jersey,Rochelle Park,3520611,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4990,44575,4989,12,Lenny & Eva,lenny-eva,Tennessee,Cookeville,5462004,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4991,20473,4990,2323,Accurate Home Care,accurate-home-care,Minnesota,Otsego,58817000,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4992,44576,4991,135,Digital Marketer,digital-marketer,Texas,Austin,14071111,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4993,8160,4992,9,Sperry Van Ness International,sperry-van-ness-international,Massachusetts,Boston,6807000,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4994,1821,4993,51,LetterLogic,letterlogic,Tennessee,Nashville,35373305,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4995,19049,4994,303,Fenwick & West,fenwick-west,California,Mountain View,363500000,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,44577,4995,104,Stonehaven Dental,stonehaven-dental,Utah,Lehi,10755433,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4997,4114,4996,105,Duffey Petrosky,duffey-petrosky,Michigan,Farmington Hills,15233132,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4998,20674,4997,22,Southridge Technology Grp,southridge-technology-grp,Connecticut,Brookfield,3713531,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999,23258,4998,1951,Stratosphere Quality,stratosphere-quality,Indiana,Fishers,102252325,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5000,9017,4999,278,Optimax Systems,optimax-systems,New York,Ontario,27989715,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5001,24552,5000,277,Murray Resources,murray-resources,Texas,Houston,5714518,3,murray-resources,3207.0,Houston,27.0,Murray Resources,Texas,11494474.0,5.0

In [332]:
inc2016_2018_cols = ["ID", "Company2016","Company2018", "Rank2016"]
inc2016_2018_transformed= inc2016_2018[inc2016_2018_cols].copy()

inc2016_2018_transformed.drop_duplicates("ID", inplace=True)
inc2016_2018_transformed.set_index("ID", inplace=True)

inc2016_2018_transformed.head()

             Company2016                  Company2018  Rank2016
ID
42940         Loot Crate                          NaN         1
42941         Paint Nite                          NaN         2
42942       CalCom Solar  California Commerical Solar         3
36643  eLuxurySupply.com                          NaN         4
36639        Company.com                          NaN         5

In [ ]:
inc2018_transformed.to_sql(name='inc2018', con=engine, if_exists='append', index=True)

In [333]:
incTEST_file = "./Resources/Fortune500_2017.csv"
incTEST_df = pd.read_csv(incTEST_file)
incTEST_df.dropna(axis=1, how='all')

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
0,1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
1,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
2,3,Apple,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
3,4,Exxon Mobil,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
4,5,McKesson,http://www.mckesson.com,68000,Wholesalers,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0
5,6,UnitedHealth Group,http://www.unitedhealthgroup.com,230000,Health Care,Health Care: Insurance and Managed Care,"Minnetonka, MN",9900 Bren Rd. E.,Minnetonka,MN,...,Chief Executive Officer & Director,"9900 Bren Rd. E., Minnetonka, MN 55343",UNH,UnitedHealth Group Incorporated,184840,17.7,7017.0,20.7,122810,38274.0
6,7,CVS Health,http://www.cvshealth.com,204000,Health Care,Health Care: Pharmacy and Other Services,"Woonsocket, RI",1 CVS Dr.,Woonsocket,RI,...,"President, Chief Executive Officer & Director","1 CVS Dr., Woonsocket, RI 02895",CVS,CVS Health Corporation,177526,15.8,5317.0,1.5,94462,36830.0
7,8,General Motors,http://www.gm.com,225000,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",300 Renaissance Center,Detroit,MI,...,Chairman & Chief Executive Officer,"300 Renaissance Center, Detroit, MI 48265",GM,General Motors Company,166380,9.2,9427.0,-2.7,221690,43836.0
8,9,AT&T,http://www.att.com,268540,Telecommunications,Telecommunications,"Dallas, TX",208 S. Akard St.,Dallas,TX,...,"Chairman, President & Chief Executive Officer","208 S. Akard St., Dallas, TX 75202",T,AT&T Inc.,163786,11.6,12976.0,-2.8,403821,123135.0
9,10,Ford Motor,http://www.ford.com,201000,Motor Vehicles & Parts,Motor Vehicles and Parts,"Dearborn, MI",1 American Rd.,Dearborn,MI,...,"President, Chief Executive Officer & Director","1 American Rd., Dearborn, MI 48126",F,Ford Motor Company,151800,1.5,4596.0,-37.7,237951,29170.0
10,11,AmerisourceBergen,http://www.amerisourcebergen.com,18500,Wholesalers,Wholesalers: Health Care,"Chesterbrook, PA",1300 Morris Dr.,Chesterbrook,PA,...,"Chairman, President & Chief Executive Officer","1300 Morris Dr., Chesterbrook, PA 19087",ABC,AmerisourceBergen Corp.,146850,8.0,1427.9,-37.7,33656,2129.0
11,12,Amazon.com,http://www.amazon.com,341400,Technology,Internet Services and Retailing,"Seattle, WA",410 Terry Ave. N.,Seattle,WA,...,"Chairman, President & Chief Executive Officer","410 Terry Ave. N., Seattle, WA 98109",AMZN,"Amazon.com, Inc.",135987,27.1,2371.0,297.8,83402,19285.0
12,13,General Electric,http://www.ge.com,295000,Industrials,Industrial Machinery,"Boston, MA",41 Farnsworth St.,Boston,MA,...,Chairman & Chief Executive Officer,"41 Farnsworth St., Boston, MA 02210",GE,General Electric Company,126661,-9.8,8831.0,297.8,365183,75828.0
13,14,Verizon,http://www.verizon.com,160900,Telecommunications,Telecommunications,"New York, NY",1095 Ave. of the Americas,New York,NY,...,Chairman & Chief Executive Officer,"1095 Ave. of the Americas, New York, NY 10036",VZ,Verizon Communications Inc.,125980,-4.3,13127.0,-26.6,244180,22524.0
14,15,Cardinal Health,http://www.cardinalhealth.com,37300,Wholesalers,Wholesalers: Health Care,"Dublin, OH",7000 Cardinal Place,Dublin,OH,...,Chairman & Chief Executive Officer,"7000 Cardinal Place, Dublin, OH 43017",CAH,"Cardinal Health, Inc.",121546,18.5,1427.0,17.4,34122,6554.0
15,16,Costco,http://www.costco.com,172000,Retailing,General Merchandisers,"Issaquah, WA",999 Lake Dr.,Issaquah,WA,...,"President, Chief Executive Officer & Director","999 Lake Dr., Issaquah, WA 98027",COST,Costco Wholesale Corporation,118719,2.2,2350.0,-1.1,33163,12079.0
16,17,Walgreens Boots Alliance,http://www.walgreensbootsalliance.com,300000,Food & Drug Stores,Food and Drug Stores,"Deerfield, IL",108 Wilmot Rd.,Deerfield,IL,...,"President, Chief Executive Officer & Director","108 Wilmot Rd., Deerfield, IL 60015",WBA,"Walgreens Boots Alliance, Inc",117351,13.4,4173.0,-1.1,72688,29880.0
17,18,Kroger,http://www.thekrogerco.com,443000,Food & Drug Stores,Food and Drug Stores,"Cincinnati, OH",1014 Vine St.,Cincinnati,OH,...,Chairman & Chief Executive Officer,"1014 Vine St., Cincinnati, OH 45202",KR,The Kroger Company,115337,5.0,1975.0,-3.1,36505,6698.0
18,19,Chevron,http://www.chevron.com,55200,Energy,Petroleum Refining,"San Ramon, CA",6001 Bollinger Canyon Rd.,San Ramon,CA,...,Chairman & Chief Executive Officer,"6001 Bollinger Canyon Rd., San Ramon, CA 94583",CVX,Chevron Corporation,107567,-18.0,-497.0,-110.8,260078,145556.0
19,20,Fannie Mae,http://www.fanniemae.com,7000,Financials,Diversified Financials,"Washington, DC",3900 Wisconsin Ave. N.W.,Washington,DC,...,"President, Chief Executive Officer & Director","3900 Wisconsin Ave. N.W., Washington, DC 20016",FNMA,Fannie Mae,107162,-2.9,12313.0,12.4,3287968,6071.0
20,21,J.P. Morgan Chase,http://www.jpmorganchase.com,243355,Financials,Commercial Banks,"New York, NY",270 Park Ave.,New York,NY,...,"Chairman, President & Chief Executive Officer","270 Park Ave., New York, NY 10017",JPM,JPMorgan Chase & Co.,105486,4.4,24733.0,1.2,2490972,254190.0
21,22,Express Scripts Holding,http://www.express-scripts.com,25600,Health Care,Health Care: Pharmacy and Other Services,"St. Louis, MO",1 Express Way,St. Louis,MO,...,"President, Chief Executive Officer & Director","1 Express Way, St. Louis, MO 63121",ESRX,Express Scripts Holding Company,100288,-1.4,3404.4,37.5,51745,16236.0
22,23,Home Depot,http://www.homedepot.com,406000,Retailing,Specialty Retailers: Other,"Atlanta, GA",2455 Paces Ferry Rd.,Atlanta,GA,...,"Chairman, President & Chief Executive Officer","2455 Paces Ferry Rd., Atlanta, GA 30339",HD,"The Home Depot, Inc.",94595,6.9,7957.0,13.5,42966,4333.0
23,24,Boeing,http://www.boeing.com,150540,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",100 N. Riverside Plaza,Chicago,IL,...,"Chairman, President & Chief Executive Officer","100 N. Riverside Plaza, Chicago, IL 60606",BA,The Boeing Company,94571,-1.6,4895.0,-5.4,89997,817.0
24,25,Wells Fargo,http://www.wellsfargo.com,269100,Financials,Commercial Banks,"San Francisco, CA",420 Montgomery St.,San Francisco,CA,...,"President, Chief Executive Officer & Director","420 Montgomery St., San Francisco, CA 94163",WFC,Wells Fargo & Company,94176,4.6,21938.0,-4.2,1930115,199581.0
25,26,Bank of America Corp.,http://www.bankofamerica.com,208024,Financials,Commercial Banks,"Charlotte, NC",100 N. Tryon St.,Charlotte,NC,...,"Chairman, President & Chief Executive Officer","100 N. Tryon St., Charlotte, NC 28255",BAC,Bank of America Corporation,93662,0.7,17906.0,12.7,2187702,266840.0
26,27,Alphabet,http://www.abc.xyz,72053,Technology,Internet Services and Retailing,"Mountain View, CA",1600 Amphitheatre Pkwy.,Mountain View,CA,...,Chief Executive Officer & Director,"1600 Amphitheatre Pkwy., Mountain View, CA 94043",GOOGL,Alphabet Inc.,90272,20.4,19478.0,19.1,167497,139036.0
27,28,Microsoft,http://www.microsoft.com,114000,Technology,Computer Software,"Redmond, WA",1 Microsoft Way,Redmond,WA,...,Chief Executive Officer & Director,"1 Microsoft Way, Redmond, WA 98052",MSFT,Microsoft Corporation,85320,-8.8,16798.0,37.8,193694,71997.0
28,29,Anthem,http://www.antheminc.com,53000,Health Care,Health Care: Insurance and Managed Care,"Indianapolis, IN",120 Monument Circle,Indianapolis,IN,...,"Chairman, President & Chief Executive Officer","120 Monument Circle, Indianapolis, IN 46204",ANTM,"Anthem, Inc.",84863,7.2,2469.8,-3.5,65083,25100.0
29,30,Citigroup,http://www.citigroup.com,219000,Financials,Commercial Banks,"New York, NY",388 Greenwich St.,New York,NY,...,Chief Executive Officer & Director,"388 Greenwich St., New York, NY 10013",C,Citigroup Inc.,82386,-6.7,14912.0,-13.5,1792077,225120.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,471,Fiserv,http://www.fiserv.com,23000,Business Services,Financial Data Services,"Brookfield, WI",255 Fiserv Dr.,Brookfield,WI,...,"President, Chief Executive Officer & Director","255 Fiserv Dr., Brookfield, WI 53045",FISV,"Fiserv, Inc.",5505,4.8,930.0,30.6,9743,2541.0
471,472,Host Hotels & Resorts,http://www.hosthotels.com,220,Financials,Real Estate,"Bethesda, MD",6903 Rockledge Dr.,Bethesda,MD,...,"President, Chief Executive Officer & Director","6903 Rockledge Dr., Bethesda, MD 20817",HST,"Host Hotels & Resorts, Inc.",5488,1.9,762.0,36.6,11408,6994.0
472,473,Insight Enterprises,http://www.insight.com,5930,Wholesalers,Wholesalers: Electronics and Office Equipment,"Tempe, AZ",6820 S. Harl Ave.,Tempe,AZ,...,"President, Chief Executive Officer & Director","6820 S. Harl Ave., Tempe, AZ 85283",NSIT,"Insight Enterprises, Inc.",5486,2.1,84.7,11.7,2219,713.0
473,474,Mattel,http://www.mattel.com,32000,Household Products,"Toys, Sporting Goods","El Segundo, CA",333 Continental Blvd.,El Segundo,CA,...,Chief Executive Officer & Director,"333 Continental Blvd., El Segundo, CA 90245",MAT,"Mattel, Inc.",5457,-4.3,318.0,-13.9,6494,2408.0
474,475,AmTrust Financial Services,http://www.amtrustgroup.com,8000,Financials,Insurance: Property and Casualty (Stock),"New York, NY",59 Maiden Lane,New York,NY,...,"Chairman, President & Chief Executive Officer","59 Maiden Lane, New York, NY 10038",AFSI,"AmTrust Financial Services, Inc.",5451,18.1,411.0,-8.8,22615,3269.0
475,476,Cincinnati Financial,http://www.cinfin.com,4754,Financials,Insurance: Property and Casualty (Stock),"Fairfield, OH",6200 S. Gilmore Rd.,Fairfield,OH,...,"President, Chief Executive Officer & Director","6200 S. Gilmore Rd., Fairfield, OH 45014",CINF,Cincinnati Financial Corporation,5449,6.0,590.7,-6.8,20386,7060.0
476,477,Simon Property Group,http://www.simon.com,4050,Financials,Real Estate,"Indianapolis, IN",225 W. Washington St.,Indianapolis,IN,...,Chairman & Chief Executive Officer,"225 W. Washington St., Indianapolis, IN 46204",SPG,"Simon Property Group, Inc.",5435,3.2,1838.9,0.6,31104,4310.0
477,478,Western Union,http://www.westernunion.com,10700,Business Services,Financial Data Services,"Englewood, CO",12500 E. Belford Ave.,Englewood,CO,...,"President, Chief Executive Officer & Director","12500 E. Belford Ave., Englewood, CO 80112",WU,The Western Union Company,5423,-1.1,253.2,-69.8,9420,902.0
478,479,KeyCorp,http://www.key.com,15700,Financials,Commercial Banks,"Cleveland, OH",127 Public Sq.,Cleveland,OH,...,"Chairman, President & Chief Executive Officer","127 Public Sq., Cleveland, OH 44114",KEY,KeyCorp,5422,19.4,791.0,-13.6,136453,15240.0
479,480,Delek US Holdings,http://www.delekus.com,1326,Energy,Petroleum Refining,"Brentwood, TN",7102 Commerce Way,Brentwood,TN,...,"Chairman, President & Chief Executive Officer","7102 Commerce Way, Brentwood, TN 37027",DK,"Delek US Holdings, Inc.",5414,-6.0,-153.7,-892.3,2985,992.0
480,481,Booz Allen Hamilton Holding,http://www.boozallen.com,22600,Technology,Information Technology Services,"McLean, VA",8283 Greensboro Dr.,McLean,VA,...,"President, Chief Executive Officer & Director","8283 Greensboro Dr., McLean, VA 22102",BAH,Booz Allen Hamilton Holding Corp.,5406,2.5,294.1,26.5,3010,409.0
481,482,Chemours,http://www.chemours.com,7000,Chemicals,Chemicals,"Wilmington, DE",1007 Market St.,Wilmington,DE,...,"President, Chief Executive Officer & Director","1007 Market St., Wilmington, DE 19899",CC,The Chemours Company,5400,2.5,7.0,26.5,6060,100.0
482,483,Western & Southern Financial Group,http://www.westernsouthern.com,2178,Financials,"Insurance: Life, Health (Mutual)","Cincinnati, OH",400 Broadway,Cincinnati,OH,...,"Chairman, President & Chief Executive Officer","400 Broadway, Cincinnati, OH 45202",CC,Western & Southern Mutual Holding Company,5398,0.8,241.2,-47.2,43831,5104.0
483,484,Celanese,http://www.celanese.com,7293,Chemicals,Chemicals,"Irving, TX",222 W. Las Colinas Blvd.,Irving,TX,...,"Chairman, President & Chief Executive Officer","222 W. Las Colinas Blvd., Irving, TX 75039",CE,Celanese Corporation,5389,-5.0,900.0,196.1,8357,2588.0
484,485,Windstream Holdings,http://www.windstream.com,11870,Telecommunications,Telecommunications,"Little Rock, AR",4001 Rodney Parham Rd.,Little Rock,AR,...,"President, Chief Executive Officer & Director","4001 Rodney Parham Rd., Little Rock, AR 72212",WIN,"Windstream Holdings, Inc.",5387,-6.6,-383.5,"-1,499.60",11770,170.0
485,486,Seaboard,http://www.seaboardcorp.com,11781,"Food, Beverages & Tobacco",Food Production,"Merriam, KS",9000 W. 67th St.,Merriam,KS,...,"Chairman, President & Chief Executive Officer","9000 W. 67th St., Merriam, KS 66202",SEB,Seaboard Corporation,5379,-3.8,312.0,82.5,4755,3162.0
486,487,Essendant,http://www.essendant.com,6600,Wholesalers,Wholesalers: Electronics and Office Equipment,"Deerfield, IL",1 Parkway N. Blvd.,Deerfield,IL,...,"President, Chief Executive Officer & Director","1 Parkway N. Blvd., Deerfield, IL 60015",ESND,Essendant Inc.,5369,0.1,63.9,82.5,2164,781.0
487,488,Apache,http://www.apachecorp.com,3727,Energy,"Mining, Crude-Oil Production","Houston, TX",2000 Post Oak Blvd.,Houston,TX,...,"President, Chief Executive Officer & Director","2000 Post Oak Blvd., Houston, TX 77056",APA,Apache Corporation,5354,-19.5,-1405.0,82.5,22519,6238.0
488,489,Airgas,http://www.airgas.com,17000,Wholesalers,Wholesalers: Diversified,"Radnor, PA",259 N. Radnor-Chester Rd.,Radnor,PA,...,Chief Executive Officer & Director,"259 N. Radnor-Chester Rd., Radnor, PA 19087",APA,"Airgas, Inc.",5314,0.2,337.5,-8.3,6135,2045.0
489,490,Kelly Services,http://www.kellyservices.com,7500,Business Services,Temporary Help,"Troy, MI",999 W. Big Beaver Rd.,Troy,MI,...,"President, Chief Executive Officer & Director","999 W. Big Beaver Rd., Troy, MI 48084",KELYA,"Kelly Services, Inc.",5277,-4.4,120.8,124.5,2028,1012.0
490,491,Liberty Media,http://www.libertymedia.com,3626,Media,Entertainment,"Englewood, CO",12300 Liberty Blvd.,Englewood,CO,...,"President, Chief Executive Officer & Director","12300 Liberty Blvd., Englewood, CO 80112",LSXMA,Liberty Media Corporation,5276,10.0,680.0,962.5,31377,11756.0
491,492,Rockwell Collins,http://www.rockwellcollins.com,19000,Aerospace & Defense,Aerospace and Defense,"Cedar Rapids, IA",400 Collins Rd. N.E.,Cedar Rapids,IA,...,"Chairman, President & Chief Executive Officer","400 Collins Rd. N.E., Cedar Rapids, IA 52498",COL,"Rockwell Collins, Inc.",5259,-0.1,728.0,6.1,7707,2078.0
492,493,Robert Half International,http://www.roberthalf.com,16400,Business Services,Temporary Help,"Menlo Park, CA",2884 Sand Hill Rd.,Menlo Park,CA,...,Chairman & Chief Executive Officer,"2884 Sand Hill Rd., Menlo Park, CA 94025",RHI,Robert Half International Inc.,5250,3.1,343.4,-4,1778,1087.0
493,494,CH2M Hill,http://www.ch2m.com,20000,Engineering & Construction,"Engineering, Construction","Englewood, CO",9191 S. Jamaica St.,Englewood,CO,...,"Chairman, President & Chief Executive Officer","9191 S. Jamaica St., Englewood, CO 80112",RHI,"CH2M HILL Companies, Ltd.",5236,-2.3,15.0,-81.3,2671,547.0
494,495,Big Lots,http://www.biglots.com,23150,Retailing,Specialty Retailers: Other,"Columbus, OH",300 Phillipi Rd.,Columbus,OH,...,"President, Chief Executive Officer & Director","300 Phillipi Rd., Columbus, OH 43228",BIG,"Big Lots, Inc.",5200,0.2,152.8,7,1608,651.0
495,496,Michaels Cos.,http://www.michaels.com,31000,Retailing,Specialty Retailers: Other,"Irving, TX",8000 Bent Branch Dr.,Irving,TX,...,Chairman & Chief Executive Officer,"8000 Bent Branch Dr., Irving, TX 75063",MIK,"The Michaels Companies, Inc.",5197,5.8,378.2,4.2,2148,-1698.0
496,497,Toll Brothers,http://www.tollbrothers.com,4200,Engineering & Construction,Homebuilders,"Horsham, PA",250 Gibraltar Rd.,Horsham,PA,...,Chief Executive Officer & Director,"250 Gibraltar Rd., Horsham, PA 19044",TOL,"Toll Brothers, Inc.",5170,23.9,382.1,5.2,9737,4229.0
497,498,Yahoo,http://www.yahoo.com,8500,Technology,Internet Services and Retailing,"Sunnyvale, CA",701 First Ave.,Sunnyvale,CA,...,"President, Chief Executive Officer & Director","701 First Ave., Sunnyvale, CA 94089",YHOO,Yahoo! Inc.,5169,4.0,-214.3,5.2,48083,31049.0
498,499,Vistra Energy,http://www.vistraenergy.com,4431,Energy,Energy,"Dallas, TX",1601 Bryan St.,Dallas,TX,...,"President, Chief Executive Officer & Director","1601 Bryan St., Dallas, TX 75201",VST,Vistra Energy Corp.,5164,4.0,-214.3,5.2,15167,6597.0
499,500,ABM Industries,http://www.abm.com,110000,Business Services,Diversified Outsourcing Services,"New York, NY",1 Liberty Plaza,New York,NY,...,"President, Chief Executive Officer & Director","1 Liberty Plaza, New York, NY 10006",ABM,ABM Industries Incorporated,5145,-2.8,57.2,-25,2281,974.0